### ISSUE TITLE
Trace drilldown to search (Trace)

### ISSUE THREAD

**Issue by jyothishjose6190** [hypertrace/hypertrace-ui#1076]
From the trace waterfall graph, cliking on a trace should take me to the explore tab with the appropriate trace id

**Comment by aaron-steinfeld** [comment]
Could you a share screenshots where you'd envision clicking and the screen you'd want to see? At first I wasn't seeing any value here, but I'm guessing now you mean going from the trace waterfall to the span explorer (vs the default trace explorer), to allow filtering the spans from that trace? If that's the case, agree shouldn't be difficult to add.

**Comment by jyothishjose6190** [comment]
@aaron-steinfeld clicking on trace id at the top of the waterfall graph should take us to the explore screen with trace id filter applied
<img width="1102" alt="Screenshot 2021-08-20 at 10 49 58 AM" src="https://user-images.githubusercontent.com/86998924/130183470-f87c175e-4527-426e-babf-a5acc146a59c.png">
<img width="1053" alt="Screenshot 2021-08-20 at 10 53 53 AM" src="https://user-images.githubusercontent.com/86998924/130183741-96ea4466-8c84-405f-984d-165cc4225f8f.png">

**Comment by aaron-steinfeld** [comment]
got it, matches what I was thinking.

**Comment by jyothishjose6190** [comment]
@aaron-steinfeld I would like to start working on this. How do you guys pass data between these pages, any standard practice you are following?

**Comment by aaron-steinfeld** [comment]
See `ExploreFilterLinkComponent` and `ExplorerService.buildNavParamsWithFilters`

**Comment by JBAhire** [comment]
Thanks, @jyothishjose6190 for picking this up!

**Comment by itssharmasandeep** [comment]
In my opinion we can extend the same component to support that. Already we're using `SummaryValueDisplayStyle` input field to support style at least, now I think we may have a input field called `Url` (which could be optional), we can use the value of this to implement navigation.
cc: @aaron-steinfeld @anandtiwary

**Comment by anandtiwary** [comment]
Just use something like this

```
            <ht-link
              [paramsOrUrl]="this.explorerNavParamsForSession$ | async"
              class="session-id-link"
            >
              <ht-summary-value></ht-summary-value>
            </ht-link>
```

**Comment by itssharmasandeep** [comment]
> Just use something like this
> 
> ```
>             <ht-link
>               [paramsOrUrl]="this.explorerNavParamsForSession$ | async"
>               class="session-id-link"
>             >
>               <ht-summary-value></ht-summary-value>  // for trace id
>             </ht-link>
> ```

But due to this label will also be clickable. Do we want that?

**Comment by anandtiwary** [comment]
Yeah that's fine. I think we are doing this at couple of places within Traceable
