### ISSUE TITLE
Trace drilldown to search (Span) 

### ISSUE THREAD

**Issue by jyothishjose6190** [hypertrace/hypertrace-ui#1086]
![Screenshot 2021-08-25 at 1 01 42 PM](https://user-images.githubusercontent.com/86998924/130746498-62c06e6f-8b22-40ba-bc41-2f6c8cb4ff37.png)
clicking on span id should take to explorer with filter applied

**Comment by itssharmasandeep** [comment]
Closing this as this is done!!
