### ISSUE TITLE
Not able to visualize span count in explorer tab 

### ISSUE THREAD

**Issue by subintp** [hypertrace/hypertrace-ui#1157]
- Count is missing the dropdown 

![Screenshot 2021-09-28 at 12 50 22 AM](https://user-images.githubusercontent.com/1742357/134971529-c2fb6b2e-8b5c-49df-984a-cd92b2da5f12.png)

**Comment by jyothishjose6190** [comment]
@JBAhire @itssharmasandeep @anandtiwary  planning to pick this issue for the current sprint. your thoughts?

**Comment by jyothishjose6190** [comment]
@anandtiwary @JBAhire  @aaron-steinfeld  these attributes are coming from the backend
![Screenshot 2021-10-13 at 8 33 34 AM](https://user-images.githubusercontent.com/86998924/137060010-4ab787da-07b9-4440-a3d1-d505a87275e4.png). Please confirm

**Comment by kotharironak** [comment]
@sarthak77 can you check what backend attributes need to be added?

**Comment by kotharironak** [comment]
@subintp What is the use case here? Do you want to count the number of spans within the aggregate window say 15s / 1min etc?

**Comment by subintp** [comment]
> What is the use case here? Do you want to count the number of spans within the aggregate window say 15s / 1min etc?

Yes. Similar to the trace count.

**Comment by sarthak77** [comment]
Merged respective PR's to add the attribute. Closing the issue now.
