### ISSUE TITLE
Explorer - Duplicate column definition name provided: "apiTraceErrorSpanCount".

### ISSUE THREAD

**Issue by jyothishjose6190** [hypertrace/hypertrace-ui#1186]
While changing metrics dropdown field to API Trace Error Span Count,   Duplicate column definition name provided: "apiTraceErrorSpanCount" error is shown in console 
![Screenshot 2021-10-12 at 11 07 17 AM](https://user-images.githubusercontent.com/86998924/136897923-1f1a6535-f758-4249-a3e4-132130dc506f.png)

**Comment by aaron-steinfeld** [comment]
This was happening in local mode only, but was resolved in https://github.com/hypertrace/hypertrace-ui/pull/1269
