### ISSUE TITLE
Explorer search filter from URL is not applied in a new window

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/hypertrace-ui#189]
Copy-paste link from the explorer page to a new tab does not include the search filter.

E.g. pasting link  `http://localhost:2020/explorer?time=6h&scope=endpoint-traces&filter=tags_ckv_client1&filter=duration_gt_50000` to a new tab does not apply any filter.

Image:
`hypertrace/hypertrace-federated-service@2246980ee71734da2b284909c51d516edf26f97a77853d6300bfa0d0d5e85375`

**Comment by jake-bassett** [comment]
Fixed.
