### ISSUE TITLE
Explorer search by tag value does not work

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/hypertrace-ui#190]
Seach by tag value seems to be broken.

For instance link `http://localhost:2020/explorer?time=6h&scope=endpoint-traces&filter=tags_ckv_client` should find instances containing a tag with value `client`. It does not find anything. It might be a UI or the query service issue.

Image:
`hypertrace/hypertrace-federated-service@2246980ee71734da2b284909c51d516edf26f97a77853d6300bfa0d0d5e85375`

**Comment by jake-bassett** [comment]
Hi Pavol. Thank you for raising the issue.

The syntax is a little confusing on that filter. It's something we are working to improve.

Can you confirm for me what you are trying to query for here? I see the `ckv` in the url, so it looks like you are using `CONTAINS_KEY_VALUE` which would expect both a key and value arg in the form `Tags CONTAINS_KEY_VALUE <key>:<value>` or for example  `Tags CONTAINS_KEY_VALUE foo:bar`.

If you instead just want to search for the presence of a key you can use `CONTAINS_KEY` in the form `Tags CONTAINS_KEY <key>` or for example `Tags CONTAINS_KEY foo`.

Does that solve the issue?

**Comment by pavolloffay** [comment]
I wanted to query all data that contain tag `span.kind=client`. The syntax `Tags CONTAINS_KEY_VALUE span.kind:client` solved my issue. 

I agree that the current syntax is not ideal and intuitive. Before submitting I talked to @JBAhire and he also doesn't seem to know how to query by tag value. There should be more examples how to query tags etc. 

I will close this issue as the search by tag works.

**Comment by JBAhire** [comment]
Thanks, Jake! 

Hey Pavol,
Let me document syntax and sample queries for all general filters and focus especially on this confusing ones! :)

**Comment by pavolloffay** [comment]
All others are trivial, maybe we could add an example of how to query tags in the UI below the search bar.
