### ISSUE TITLE
Sharing trace fragment or full trace URL is broken

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/hypertrace-ui#192]
Pasting link of a full trace e.g. `http://localhost:2020/trace/0000000000000000448c201de656eca7?time=2w` yields in

![Screenshot of Error 404 Not Found](https://user-images.githubusercontent.com/5618424/93091769-d494ab00-f69e-11ea-802d-9384265c9155.png)

The same error happens when sharing a trace fragment:

![Screenshot of Hypertrace (4)](https://user-images.githubusercontent.com/5618424/93091856-f5f59700-f69e-11ea-8900-2c5122f4de17.png)

Image:
hypertrace/hypertrace-federated-service@2246980ee71734da2b284909c51d516edf26f97a77853d6300bfa0d0d5e85375

**Comment by jcchavezs** [comment]
Is this still happening @pavolloffay? I just checked myself and it worked. Maybe the `time` is the problem?

**Comment by pavolloffay** [comment]
I haven't tested it again. Close this if you cannot reproduce.

I can give it a try once I will run HT.

**Comment by aaron-steinfeld** [comment]
This is the same issue as https://github.com/hypertrace/hypertrace/issues/71 - now resolved.

**Comment by kotharironak** [comment]
closing this, pl. reopen if this is still happening.
