### ISSUE TITLE
Make the color scheme in trace detail view more distinct

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/hypertrace-ui#193]
The colors used for services in the trace detail view are too similar. it's hard to distinguish different services. 

![Screenshot of Hypertrace (5)](https://user-images.githubusercontent.com/5618424/93110056-192b4100-f6b5-11ea-8ab4-e1c744d88417.png)

**Comment by jake-bassett** [comment]
Going to take this as good feedback, but waiting for more before we make any further changes.
