### ISSUE TITLE
SassError: Can't find stylesheet to import.

### ISSUE THREAD

**Issue by chcheruk** [hypertrace/hypertrace-ui#27]
I am running into the following error while running the npm start. Can someone help?

node --version
v13.11.0
 
npm --version
6.13.7

npm start

> hypertrace-ui@0.0.0 start /PWD/rc/hypertrace-ui
> ng serve

chunk {main} main.js, main.js.map (main) 2.11 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 694 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 10 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 341 kB [initial] [rendered]
Date: 2020-07-15T16:44:09.832Z - Hash: 74796545cc961a28ac2e - Time: 5054ms

ERROR in Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import 'font';
  │         ^^^^^^
  ╵
  /PWD/rc/hypertrace-ui/projects/observability/src/pages/explorer/explorer.component.scss 1:9  root stylesheet
ERROR in ./src/styles/main.scss (./node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/postcss-loader/src??embedded!./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js??ref--13-3!./src/styles/main.scss)
Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import 'layout';
  │         ^^^^^^^^
  ╵
  /PWD/rc/hypertrace-ui/src/styles/main.scss 1:9  root stylesheet
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

**Comment by anandtiwary** [comment]
@chcheruk We are using git submodules in hypertrace-ui. You might not have initialized it after you cloned the repo. Please try after running the following command.

`git submodule update --init`

We will post a detailed instruction in readme soon.

**Comment by anandtiwary** [comment]
Closing the issue. Let me know if you face any issue again!

**Comment by chcheruk** [comment]
Hi Anand, Still running into the same problem after trying your input.

**Comment by anandtiwary** [comment]
It should work with that command. We don't need to run npm install on hypertrace-core-ui. 

May be you are in a bad git state? 
Try this
1. git checkout master
2. git reset --hard HEAD~10
3. git pull --recurse-submodules

**Comment by chcheruk** [comment]
@anandtiwary Above commands solved the problem. Appreciate all the help.

**Comment by chcheruk** [comment]
You can close the issue. thanks

**Comment by anandtiwary** [comment]
Awesome! Thank you for trying it out!
