### ISSUE TITLE
Trace detail: service names for a large trace should not be individually scrollable 

### ISSUE THREAD

**Issue by pavolloffay** [hypertrace/hypertrace-ui#411]
The screen shouldn't be split into two half - service name  and gantt diagram. When user scrolls down both view should scroll down - otherwise it is impossible to correlate service name/op name with the span on the right.

![Screenshot of Traceable (3)](https://user-images.githubusercontent.com/5618424/101166743-10556600-3639-11eb-9344-5523af93b78b.jpg)

**Comment by aaron-steinfeld** [comment]
Will fix the scrolling - that's a bug. There's a number of other pre-existing issues on the page that will leave as later work.
