### ISSUE TITLE
Bug: Wrong tooltip is showing for radar chart

### ISSUE THREAD

**Issue by subintp** [hypertrace/hypertrace-ui#748]
Probelm:
Wrong tooltip is showing on hovering on radar chart. 

How to reproduce:
1. Go to Dashboard (Use firefox)
2. Click on Errors/Second metric from radar chat
3. P99 latency will be shown in the tooltip
4. Erros/Second is expected in the tooltip on hovering Errros/Second

Screenshot after clicking errors/second:
<img width="1381" alt="Screenshot 2021-03-17 at 12 29 02 PM" src="https://user-images.githubusercontent.com/1742357/113672203-0a4dbf80-96d5-11eb-99e8-5caf165bb897.png">

**Comment by JBAhire** [comment]
@anandtiwary @itssharmasandeep , there's something wrong with data as well. Here you can clearly see that error rate is high for last 1 hour than last 12 hours but the radar is not able to show it properly.

<img width="690" alt="Screenshot 2021-04-22 at 1 36 07 PM" src="https://user-images.githubusercontent.com/26570044/115679623-6751a280-a370-11eb-86c4-c689fce84a2c.png">

**Comment by jyothishjose6190** [comment]
started working on this issue
